stages:
    - build

Build binary package:
    stage: build
    image: python:3.8-slim-bullseye
    rules:
        - if: '$CI_COMMIT_TAG =~ /^[0-9]+\./'
          when: always
        - when: never
    before_script:
        - pip3 install pyinstaller
        - apt-get update && apt-get install -y binutils curl
        - sed -i "s/version = .*/version = '$CI_COMMIT_TAG'/g" pkctl.py
    script:
        - pip3 install -r requirements.txt
        - pyinstaller pkctl.py --onefile --name pkctl-$CI_COMMIT_TAG
    after_script:
       - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file dist/pkctl-$CI_COMMIT_TAG "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/my_package/${CI_COMMIT_TAG}/pkctl-$CI_COMMIT_TAG"'